Document: grub2-remenu
Title: Debian grub2-remenu Manual
Author: <insert document author here>
Abstract: This manual describes what grub2-remenu is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/grub2-remenu/grub2-remenu.sgml.gz

Format: postscript
Files: /usr/share/doc/grub2-remenu/grub2-remenu.ps.gz

Format: text
Files: /usr/share/doc/grub2-remenu/grub2-remenu.text.gz

Format: HTML
Index: /usr/share/doc/grub2-remenu/html/index.html
Files: /usr/share/doc/grub2-remenu/html/*.html
